version: 2.1
commands:
    setup:
        steps:
            - checkout
            - run:
                name: setup Qemu
                command: |
                  docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            - run:
                name: Create builder
                command: |
                  export DOCKER_CLI_EXPERIMENTAL=enabled
                  docker context create multi-arch-build
                  docker buildx create --use multi-arch-build
jobs:
    build:
        docker:
          - image: docker:dind
        resource_class: small
        steps:
            - setup_remote_docker
            - setup
            - checkout
            - run:
                name: Login Registry
                command: |
                  echo "${REGISTRY_PASSWORD}" | docker login ${REGISTRY_DOMAIN} --username ${REGISTRY_USER} --password-stdin
            - run:
                 name: Build multiarch docker image
                 command: |
                   DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build  --platform linux/ppc64le,linux/s390x,linux/arm64,linux/amd64 -t ${REGISTRY_URL}/hello_world_go:latest
            - run:
                name: Build multiarch docker image and push
                command: |
                  DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --push --platform linux/ppc64le,linux/s390x,linux/arm64,linux/amd64 -t ${REGISTRY_URL}/hello_world_go:latest .
workflows:
    version: 2
    build-and-push-multi-arch-image:
        jobs:
            - build